# Generated by Django 3.2.8 on 2021-10-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211014_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zastavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='zastavka', verbose_name='Картинка')),
                ('nazvanie', models.CharField(max_length=50, verbose_name='Название')),
                ('opisanie', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Заставка',
                'verbose_name_plural': 'Заставки',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.Tag', verbose_name='тЭги'),
        ),
    ]
